project:
  type: website
  output-dir: docs

website:
  title: "統計解析 講義・演習リンク集"
  navbar:
    left:
      - href: index.qmd
        text: ホーム
  sidebar:
    style: docked
    contents: auto
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    freeze: auto
